#web server port
server:
  port: "8080"

#使用openssl rand -base64 64指令在bash產生金鑰
jwt:
  secret: YOUR_SECRET_KEY

spring:
  application:
    name: DesignerShop_backend
  #mysql server setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/designershop?serverTimezone=Asia/Taipei&characterEncoding=UTF-8
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
  #setting data JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    open-in-view: 'false'
  #啟用或禁用驗證，驗證訊息本地化
  mvc:
    validation:
      enabled: 'true'
      locale: zh_TW
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_GOOGLE_ACCOUNT@gmail.com
    password: YOUR_APPLICATION_PASSWORD
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: 'true'
          starttls:
            enable: 'true'
    default-encoding: UTF-8